import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Header} from "@/components/Layout/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-black-primary`}>
      <Header/>
      <div className={"xs:w-full md:w-[90%] xl:w-[1124px] mx-auto mt-[56px]"}>

      {children}
      </div>
      </body>
    </html>
  )
}
